#+title: Timesheet for Sripathi K 
#+Author: Sripathi Kammari

* Monthly Report - October


I have assigned to OVPL team on 2014-09-26 Fri. As I am begining to this team I took intiation to understand OVPL archietecture and then I started learning technologies with respect to the OVPL.

** Understands OVPL architecture.

- As part of lik release I have prepared a document which explains OVPL dependencies script files.
- Learnt about tornado python web framework and python logging module.
- Tirumala Sir told me to read on python coding conventions I started learning, finished it.
- Took hands on session to UI team about tornado web frame work server.
- Added comments to ControllerServer.py file with my understanding.

** Centralized logging server

- I worked with Tirumala Sir in writing Centralized logging code and I took his help in understanding code and he explained me how it works.
- Next day I started Working on testing with partial Centralized logging code and it's done.
- Meeting was conducted then to list out the tasks to be carried out ahead. I and Amulya was given the task to test the Centralized logging service. We were getting error while deploying the lab. we report it to Tirumala.
- I myself worked on whole saturday on debugging that error while deploying lab in Centralized logging code but it didn't worked out.
- Given help to UI team in storing values in to mysql db using python also regarding tornado web server.

** Took session on Git version control

- Given basic idea about Git version control systems to Geetha, zubir and Vinutha.
- Explained Git commands too. 
   
** Worked on Websockets

- Worked on websockets for couple of days and developed sample websockets using tornado web framework application.
- I took leave on 27 th. 
